Implement UI and basic features
FirebaseExtended/make-it-so-android pull request #54
Opened 2024-12-16 10:37 UTC by marinacoelho

This pull request implements the UI for all screens, adds a dark theme and `snackbar` to give users feedback on their actions. It also connects this UI to the functions that were previously created in the `DataSource` files.

2025-01-17 15:18 UTC, thatfiredev requested changes

2025-01-17 15:18 UTC, thatfiredev commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/shared/LoadingIndicator.kt
> +    ConstraintLayout(modifier = Modifier.fillMaxSize()) {
Out of curiosity: Why are we using ConstraintLayout here? It looks like the same could be achieved with a `Box`.

2025-01-17 15:18 UTC, thatfiredev commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/home/HomeScreen.kt
> +    else HomeScreenContent(openSettingsScreen, viewModel)
It's a [Kotlin convention](https://kotlinlang.org/docs/coding-conventions.html#control-flow-statements) to always use curly braces in a multiline `if` statement:
> If the condition of an if or when statement is multiline, always use curly braces around the body of the statement.

```suggestion
    if (isLoadingUser) {
        LoadingIndicator()
    } else {
        HomeScreenContent(openSettingsScreen, viewModel)
    }
```

2025-01-17 15:18 UTC, thatfiredev commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/settings/SettingsScreen.kt
> +    }
nit: for better readability, it might be better to use named arguments when calling Standard Button so we know what this lambda does. Eg.

```kotlin
StandardButton(
  label = R.string.delete_account,
  onButtonClick = {
    showDeleteAccountDialog.value = true
  }
)
```

Applies throughout.

2025-01-17 15:18 UTC, thatfiredev commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/settings/SettingsScreen.kt
> +    if (showDeleteAccountDialog.value) {
nit: you can initialize the `showDeleteAccountDialog` with:

```kotlin
var showDeleteAccountDialog by remember { mutableStateOf(false) }
```

So that this if statement becomes:
```kotlin
if (showDeleteAccountDialog) {
```

2025-01-17 15:18 UTC, thatfiredev commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/settings/SettingsViewModel.kt
> +    fun signOut(openHomeScreen: () -> Unit) {
I don't like the idea of passing callbacks to the ViewModel. I think `openHomeScreen()` should be called by the UI layer, not the ViewModel. The ViewModel should simply handle signing out the user. The UI is responsible for whatever happens after the user is signed out.

2025-01-21 12:47 UTC, marinacoelho commented on v2/gradle/libs.versions.toml
> +firebase-crashlytics = { id = "com.google.firebase.crashlytics"}
Good catch, it was a test that I forgot to remove! Updated this and the `ksp` library that was also duplicated.

2025-01-21 12:48 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/MainViewModel.kt
> +        private const val GENERIC_ERROR = "Something went wrong"
Changed the approach to error logging so we can store all errors in the `string` file.

2025-01-21 12:48 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/data/model/TodoItem.kt
> +}
Great idea - done!

2025-01-21 12:49 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/signup/SignUpViewModel.kt
> +        private const val PASSWORDS_DO_NOT_MATCH_ERROR = "Passwords do not match"
Done

2025-01-21 14:11 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/data/datasource/TodoItemRemoteDataSource.kt
> +            authDataSource.currentUserIdFlow.flatMapLatest { ownerId ->
This code is here in case the user is deleted from the user base (therefore, the current user id would become null and we would stop fetching their todo items)

2025-01-21 14:16 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/data/datasource/TodoItemRemoteDataSource.kt
>  class TodoItemRemoteDataSource @Inject constructor(
There are two main reasons why I decided for this approach:

1. It's in line with [Android's Naming convention for Data Sources](https://developer.android.com/topic/architecture/data-layer#naming-conventions), which tells us to avoid naming the data source based on an implementation detail
2. The next features that we're going to add to the "TodoList" and "TodoItem" screens are going to add more complex logic to these Data Sources, I think it will be cleaner and more readable if we keep those separate

2025-01-21 14:50 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/shared/LoadingIndicator.kt
> +    ConstraintLayout(modifier = Modifier.fillMaxSize()) {
This was a personal preference to be honest -  also `ConstraintLayout` gives us a lot of flexibility if we want to grow the Loading UI at some point

2025-01-21 14:59 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/settings/SettingsScreen.kt
> +    }
Fixed all calls to `StandardButton`.

2025-01-21 15:00 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/settings/SettingsScreen.kt
> +    if (showDeleteAccountDialog.value) {
Great catch - done!

2025-01-21 15:05 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/data/repository/TodoItemRepository.kt
>  class TodoItemRepository @Inject constructor(
Same answer as above: The next features that we're going to add to the "TodoList" and "TodoItem" screens are going to add more complex logic to these Repositories, I think it will be cleaner and more readable if we keep those separate

2025-01-21 15:32 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/data/datasource/TodoItemRemoteDataSource.kt
> +    private val authDataSource: AuthRemoteDataSource,
Done!

2025-01-21 18:13 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/settings/SettingsViewModel.kt
> +    fun signOut(openHomeScreen: () -> Unit) {
Updated navigation logic according to the Android architecture!

2025-01-28 14:11 UTC, thatfiredev commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/shared/LoadingIndicator.kt
> +    ConstraintLayout(modifier = Modifier.fillMaxSize()) {
I think we're adding too much complexity for something that _might_ happen in the future. Plus, a `Box` would be less code compared to `ConstraintLayout`.

2025-01-28 14:22 UTC, thatfiredev commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/settings/SettingsScreen.kt
> +fun DeleteAccountButton(viewModel: SettingsViewModel = hiltViewModel()) {
Not sure if it's a good idea to pass the viewModel to a button. Maybe we could pass a `onDeleteAccountClicked()` function instead?

2025-01-28 18:06 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/shared/LoadingIndicator.kt
> +    ConstraintLayout(modifier = Modifier.fillMaxSize()) {
Yes, that's fair! Changed to `Box`.

2025-01-28 18:09 UTC, marinacoelho commented on v2/app/src/main/java/com/google/firebase/example/makeitso/ui/settings/SettingsScreen.kt
> +fun DeleteAccountButton(viewModel: SettingsViewModel = hiltViewModel()) {
Done!

2025-01-28 18:55 UTC, thatfiredev approved these changes
LGTM

2025-01-29 12:09 UTC, merged